3 4 generics
thinknetica-django-lab-03/alex-apk pull request #31
Opened 2021-06-03 14:35 UTC by alex-apk

Closes #24

2021-06-03 14:39 UTC, alex-apk commented
Знаю, что выглядят шаблоны на редкость убого, но с фронтендом у меня совсем не очень дела обстоят. Также не уверен в том, что правильно сделал генерацию урлов в списках - работать-то она работает, но если урлы поменяются в urls.py - работать они перестанут. Вероятно, должен быть какой-то более правильный способ генережки урлов, но мне показалось, что в шаблонах для списков настолько много общего, что различаются у них разве что заголовки (да и те можно было бы в контекст вынести, на самом деле), поэтому они наследуют по-максимуму от base_list_view. Схожая ситуация и с DetailView. В общем, понимаю, что в этот раз получилось не очень, хотелось бы чуть больше подробностей в направлении "куда копать".

2021-06-04 08:56 UTC, mikhailborodin requested changes

2021-06-04 08:56 UTC, mikhailborodin commented on thinkvito/main/templates/main/header.html
> +          <a class="dropdown-item" href="/cars">Cars</a>
урлы в шаблонах лучше писать через встроенный тэг, например `{% url '<url-name>' %}`

2021-06-04 08:56 UTC, mikhailborodin commented on thinkvito/main/views.py
> +        add_context = {
это не нужно добавлять в контекст, в шаблоне есть доступ к этим данных через object. Например в шаблоне можно написать `{{ object.model }}`

2021-06-04 10:45 UTC, alex-apk commented
Урлы пофиксил.

Мотивация для использования контекста такая:
1. В том варианте верстки, который я выбрал для `DetailView`, каждое поле оборачивается в `<li class="list-group-item">`. Показалось логичным вынести этот фрагмент в базовый темплейт для всех `DetailView`, ибо эта часть одинаковая для всех `DetailView`.
2. В этом случае возникает проблема - базовому темплейту нужно откуда-то получить информацию о дополнительных полях в той модели, которую он рендерит, более того - ему нужно знать, как выводить "имя" этого поля (т.е. например `object.created` выводится как "Posted"). Пробовал его выводить через `object.category.verbose_name`, но в этом случае не выводится вообще ничего.
3. Также есть необходимость управлять порядком вывода полей модели - т.е. чтобы сначала шла категория, затем сразу стоимость, поля, характерные для конкретно этой модели - обязательно в конце, и т.п. Как этого добиться простым обходом вида `{% for k, v in object.items %}` - я не представляю.


Отсюда решение - поместить "выводимое имя" и значение поля в контекст (в чем особенно помогает то, что питон с версии 3.6 сохраняет порядок вставки ключей в словарь).

2021-06-04 20:37 UTC, mikhailborodin approved these changes

2021-06-05 18:18 UTC, merged