4 1 filters and pagination
thinknetica-django-lab-03/alex-apk pull request #32
Opened 2021-06-04 14:36 UTC by alex-apk

Closes #19

2021-06-05 20:50 UTC, mikhailborodin requested changes

2021-06-05 20:50 UTC, mikhailborodin commented on thinkvito/main/views.py
> +    def dispatch(self, request, *args, **kwargs):
метод dispatch тут не нужен, у нас уже есть в контексте список тэгов, которые можно вывести в шаблон. Непонятно зачем нам ещё tag_str делать

2021-06-05 22:18 UTC, alex-apk commented on thinkvito/main/views.py
> +    def dispatch(self, request, *args, **kwargs):
Список тэгов в шаблоне действительно подтягивается из контекста. В dispatch мы смотрим, передал ли браузер в get-параметрах тэг (т.е. смотрит ли пользователь страницу с выбранным тэгом, или просматривает вообще все объявления). Если тэг выбран - из него собирается get-параметр и кладется в tag_str, который в контексте передается шаблону, чтобы сконструировать корректные ссылки на следующую/предыдущую страницу (чтобы они так же просматривались с выбранным тэгом. Если браузер не передал get-параметр tag, то в tag_str будет пустая строка, и соответственно ссылки на следующую/предыдущую страницу будут отрендерены без get-параметров. Там в шаблоне видно, где tag_str применяется.
Если не переопределять dispatch, то можно эту логику и в get_context_data положить, конечно, но в целом интересно, скорее, что считается best practice в случае, когда нужно менять ссылки в пагинаторе в зависимости от переданных клиентом get-параметров.

2021-06-07 20:33 UTC, mikhailborodin commented on thinkvito/main/views.py
> +    def dispatch(self, request, *args, **kwargs):
метод dispatch всё-таки нужен для других целей – направлять на нужный метод. Обработку get параметров из запроса лучше осуществлять ближе к шаблону

2021-06-07 20:33 UTC, mikhailborodin approved these changes

2021-06-07 22:47 UTC, merged